- name: Copy garbage collection service
  copy:
    src: registry-gc.service
    dest: /etc/systemd/system/registry-gc.service
    mode: '0644'

- name: Copy garbage collection timer
  copy:
    src: registry-gc.timer
    dest: /etc/systemd/system/registry-gc.timer
    mode: '0644'

- name: Enable garbage collection timer
  systemd:
    name: registry-gc.timer
    enabled: yes
    state: started
    daemon_reload: yes
